AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-rest-api-hands-on

  Sample SAM Template for sam-rest-api-hands-on

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Runtime: java11
    Architectures:
      - x86_64
    MemorySize: 512

Resources:
  FirstSamRestApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: RestApiFunction
      Handler: com.studies.aws.sam.PostHandler::handleRequest    
      Events:
        FirstSamRestApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FirstSamRestApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
  FirstSamRestApiFunction:
    Description: "FirstSamRestApiFunction ARN"
    Value: !GetAtt FirstSamRestApiFunction.Arn
  FirstSamRestApiFunctionIamRole:
    Description: "Implicit IAM Role created for FirstSamRestApiFunction"
    Value: !GetAtt FirstSamRestApiFunctionRole.Arn
