openapi: "3.0.1"
info:
  title: "SamUserApiStack"
  version: "1.0"
servers:
- url: "https://6uhrx50lpl.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/Prod"
paths:
  /users:
    post:
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:423042476254:function:SamUserApiStack-CreateUserFunction-2NQCUEeJAdLm/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /login:
    post:
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:423042476254:function:SamUserApiStack-LoginUserFunction-xmu27oXlxtos/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /users/me:
    get:
      parameters:
      - name: "accessToken"
        in: "header"
        required: true
        schema:
          type: "string"
      security:
      - SamUserApiAuthorizer: []
      x-amazon-apigateway-request-validator: "Validate query string parameters and\
        \ headers"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:423042476254:function:SamUserApiStack-GetUserHandlerFunction-GaOgKd5SawJ4/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /confirm:
    post:
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:423042476254:function:SamUserApiStack-ConfirmUserFunction-pBQKqWpCzrHH/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /users/{userName}/add-to-group:
    post:
      parameters:
      - name: "userName"
        in: "path"
        required: true
        schema:
          type: "string"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:423042476254:function:SamUserApiStack-AddUserToGroupFunction-QS9OFiz58gZW/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
components:
  securitySchemes:
    SamUserApiAuthorizer:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
      x-amazon-apigateway-authorizer:
        providerARNs:
        - "arn:aws:cognito-idp:us-east-1:423042476254:userpool/us-east-1_ADVwJvZRZ"
        type: "cognito_user_pools"
x-amazon-apigateway-request-validators:
  Validate query string parameters and headers:
    validateRequestParameters: true
    validateRequestBody: false
